#+title: The Agency Problem
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

You can also see this video:

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/MI4BCgS883c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export

* The Goal of Financial Management

To enable more equity financing (as well as to allow limited liability), we separate the ownership and control of the firm.  Control of the firm is held by the shareholders, however this control is delegated to professional management. Management is referred to as an **agent** of the shareholders.

Because of the delegated control it is important that management is given a clear and unambiguous goal.  This goal is:

#+begin_quote
Maximize Shareholder Wealth.
#+end_quote

But does this guarantee that management will do so?

* The Agency Problem

The *agency problem* is when management (the agent) puts their own interest before maximizing shareholder wealth.  The reduction in shareholder wealth due to an agency problem is known as an *agency cost*.

The agency problem (and agency costs) are always present when there is a separation of ownership and control.  However, the severity of the agency problem can vary widely, and is affected by management (agent) incentives, laws, and the extent to which laws are enforced.

Some agency costs are clear, and others are subtle.  Below we discuss two brad types of agency costs with examples.

* Direct Agency Costs

- Excessive Pay
- Auditor payments.

#+BEGIN_QUOTE
The debate about a straw man.  Media and some corporate finance textbooks will often ask the question, is CEO pay excessive?  They then say well Oprah and LeBron James also make a lot of money and we have free markets, so no it is not excessive.  Some textbooks will also cite CEO's like Oracle's Larry Ellison without noting that Larry is has a huge ownership stake as well as being CEO (management).

The sleight-of-hand being done here is that no one thinks shareholders can't pay the CEO whatever they want.  The issue is precisely that the present financial and legal structure *hinders shareholders ability to set CEO pay*.  Stated simply, CEO pay is a symptom of an underlying problem, and it is not the problem itself.  So you can't discuss the symptom while not naming the cause. 

To effectively affect CEO pay you need to own a significant enough stake in the company to:

1.  Separate the CEO title from the Chairman title---think about what the dual title means.
2.  Affect the nomination of the slate of Board of Directors to be voted on.

Now consider the regulation that required you to file a Schedule 13-D with the SEC within 10 days of acquiring a 5% stake in the company. Also consider much of a company's stock is held by investors through funds, and the fund votes their shares for them.

To see how little shareholders affect executive compensation, see the [[https://www.sec.gov/Archives/edgar/data/320193/000119312514008074/d648739ddef14a.htm][2014 proxy statement Apple Inc.]]  Shareholders will vote on, "A non-binding advisory resolution to approve executive compensation (Proposal No. 6)".
#+END_QUOTE


* Indirect Agency Costs

- Management does not take a risky positive net present value project for fear of losing their jobs if the project fail.
- The CEO acquires other companies to make their own company larger (empire building), thereby raising pay and social status.
  
* Solving the Agency Problem:  The Market for Corporate Control

If the agency problem gets too large, the stock price should fall.  As the stock price falls, it becomes cheaper and cheaper to buy the firm's assets.  Eventually investors will start bidding to acquire the firm, and once they do, the present management if often replaced.

In such fashion, acquisitions represent the most effective solution to the agency problem.  The only drawback is the agency problem must become quite large before acquisitions will be attempted.

You may have heard that often corporations have anti-takeover amendments in their article of incorporation.  What effect do you think this has on the agency problem?  

* SEC DEF14A 

The form [[https://www.sec.gov/fast-answers/answersproxyhtfhtm.html][SEC Def 14A]] is a company's annual /definitive/ proxy statement.  A proxy statement outlines what shareholders will vote on at the annual meeting.

* Assignment

Pick a company which name starts with the same letter as the first letter of your last name.  For example, my last name starts with *B*, so I could choose *Boeing* (ticker BA).  If you are having a hard time finding a company, [[https://iextrading.com/apps/stocks/][just go here and type in the first letter of your last name in the search bar at the top]].

Once you have a company, search [[https://www.sec.gov/edgar/searchedgar/companysearch.html][the filings for the latest DEF14A here.]]  Use the filing to answer the following questions.

1.  Is the CEO also Chairman of the Board?
2.  Who are the directors and what is their pay?
3.  Who is the firm's auditor?

Upload your answers to the Blackboard dropbox.

#+BEGIN_COMMENT
<!-- ideas for interactive app -->
<!-- can we query somthing from SEC? -->

<!--- maybe pull SEC forms for a given company -->

<!--- find company's which may have have an agency problem becuase of high levels of employee ownership -->
<!--- 11-K 	Annual reports of employee stock purchase, savings and similar plans pursuant to Section 15(d) (PDF) -->
<!--- Who owns the companys, find companies with blockholders -->
<!--- 3 	Initial statement of beneficial ownership of securities (PDF) -->
#+END_COMMENT







# just a test to see if an app works---it does.
#+BEGIN_COMMENT
#+BEGIN_EXPORT html
  <div>
    <iframe src="https://micfm.shinyapps.io/compounding_app1/" height="600px" width="100%"></iframe>
  </div>
#+END_EXPORT
#+END_COMMENT
